// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Netlify DB injects NETLIFY_DB_URL, not DATABASE_URL — support both so
    // local dev (DATABASE_URL in .env) and Netlify both work.
    url: process.env["DATABASE_URL"] ?? process.env["NETLIFY_DB_URL"],
  },
});
